// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5lxImbOgsuiSLtQIm54s6gmpp0Ih4mQ8',
    appId: '1:148013833254:web:273d671427ab8285545ae7',
    messagingSenderId: '148013833254',
    projectId: 'layover-friends',
    authDomain: 'layover-friends.firebaseapp.com',
    storageBucket: 'layover-friends.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqsdWHMJIdrfDsQUSZAFVXoRu-4cyhZFs',
    appId: '1:148013833254:android:61fe2f548e77b3d0545ae7',
    messagingSenderId: '148013833254',
    projectId: 'layover-friends',
    storageBucket: 'layover-friends.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjHCpraWB0OU0sjTiSwovaP95HV8gnfRI',
    appId: '1:148013833254:ios:8a48cef55ce8f03d545ae7',
    messagingSenderId: '148013833254',
    projectId: 'layover-friends',
    storageBucket: 'layover-friends.firebasestorage.app',
    iosBundleId: 'com.example.layoverFriends',
  );
}
